<?php

define( 'QI_ADDONS_FOR_ELEMENTOR_VERSION', '1.5.7' );
define( 'QI_ADDONS_FOR_ELEMENTOR_ABS_PATH', dirname( __FILE__ ) );
define( 'QI_ADDONS_FOR_ELEMENTOR_REL_PATH', dirname( plugin_basename( __FILE__ ) ) );
define( 'QI_ADDONS_FOR_ELEMENTOR_URL_PATH', plugin_dir_url( __FILE__ ) );
define( 'QI_ADDONS_FOR_ELEMENTOR_ASSETS_PATH', QI_ADDONS_FOR_ELEMENTOR_ABS_PATH . '/assets' );
define( 'QI_ADDONS_FOR_ELEMENTOR_ASSETS_URL_PATH', QI_ADDONS_FOR_ELEMENTOR_URL_PATH . 'assets' );
define( 'QI_ADDONS_FOR_ELEMENTOR_INC_PATH', QI_ADDONS_FOR_ELEMENTOR_ABS_PATH . '/inc' );
define( 'QI_ADDONS_FOR_ELEMENTOR_INC_URL_PATH', QI_ADDONS_FOR_ELEMENTOR_URL_PATH . 'inc' );
define( 'QI_ADDONS_FOR_ELEMENTOR_ADMIN_PATH', QI_ADDONS_FOR_ELEMENTOR_INC_PATH . '/admin' );
define( 'QI_ADDONS_FOR_ELEMENTOR_ADMIN_URL_PATH', QI_ADDONS_FOR_ELEMENTOR_INC_URL_PATH . '/admin' );
define( 'QI_ADDONS_FOR_ELEMENTOR_SHORTCODES_PATH', QI_ADDONS_FOR_ELEMENTOR_INC_PATH . '/shortcodes' );
define( 'QI_ADDONS_FOR_ELEMENTOR_SHORTCODES_URL_PATH', QI_ADDONS_FOR_ELEMENTOR_INC_URL_PATH . '/shortcodes' );
define( 'QI_ADDONS_FOR_ELEMENTOR_PLUGINS_PATH', QI_ADDONS_FOR_ELEMENTOR_INC_PATH . '/plugins' );
define( 'QI_ADDONS_FOR_ELEMENTOR_PLUGINS_URL_PATH', QI_ADDONS_FOR_ELEMENTOR_INC_URL_PATH . '/plugins' );

define( 'QI_ADDONS_FOR_ELEMENTOR_ACTIVATED_TRANSIENT', 'qi_addons_for_elementor_plugin_activated' );
define( 'QI_ADDONS_FOR_ELEMENTOR_DISABLED_WIDGETS', 'qi_addons_for_elementor_disabled_widgets' );
